IF
	Die()
THEN
	RESPONSE #100
		DestroyItem("SYMRBRT")
		DestroySelf()
END

IF
	!GlobalGT("initialize","LOCALS",0)
	OR(2)
		AreaType(OUTDOOR)
		AreaType(FOREST)
THEN
	RESPONSE #100
		SetGlobal("initialize","LOCALS",1)
		SetGlobalTimer("Existime","LOCALS",600)
		ReallyForceSpellRES("SYMUAV3A",Myself)
		SetGlobal("ACTVMODE","LOCALS",1)
		DisplayStringHead(Myself,@151)	//室外环境，可高空飞行。攻击模式默认开启
		Continue()
END

IF
	!GlobalGT("initialize","LOCALS",0)
	!AreaType(OUTDOOR)
	!AreaType(FOREST)
THEN
	RESPONSE #100
		SetGlobal("initialize","LOCALS",1)
		SetGlobalTimer("Existime","LOCALS",600)
		ReallyForceSpellRES("SYMUAV3B",Myself)
		SetGlobal("ACTVMODE","LOCALS",1)
		DisplayStringHead(Myself,@152)	//室内环境，可低空飞行，请小心障碍物。攻击模式默认开启
		Continue()
END

//如果存在召唤者，则判断召唤者是第几个，记录
IF
	!GlobalGT("mycontroller","LOCALS",0)
	Exists(LastSummonerOf())
	InPartySlot(LastSummonerOf(),0)
THEN
	RESPONSE #100
		SetGlobal("mycontroller","LOCALS",1)
		Continue()
END

IF
	!GlobalGT("mycontroller","LOCALS",0)
	Exists(LastSummonerOf())
	InPartySlot(LastSummonerOf(),1)
THEN
	RESPONSE #100
		SetGlobal("mycontroller","LOCALS",2)
		Continue()
END

IF
	!GlobalGT("mycontroller","LOCALS",0)
	Exists(LastSummonerOf())
	InPartySlot(LastSummonerOf(),2)
THEN
	RESPONSE #100
		SetGlobal("mycontroller","LOCALS",3)
		Continue()
END

IF
	!GlobalGT("mycontroller","LOCALS",0)
	Exists(LastSummonerOf())
	InPartySlot(LastSummonerOf(),3)
THEN
	RESPONSE #100
		SetGlobal("mycontroller","LOCALS",4)
		Continue()
END

IF
	!GlobalGT("mycontroller","LOCALS",0)
	Exists(LastSummonerOf())
	InPartySlot(LastSummonerOf(),4)
THEN
	RESPONSE #100
		SetGlobal("mycontroller","LOCALS",5)
		Continue()
END

IF
	!GlobalGT("mycontroller","LOCALS",0)
	Exists(LastSummonerOf())
	InPartySlot(LastSummonerOf(),5)
THEN
	RESPONSE #100
		SetGlobal("mycontroller","LOCALS",6)
		Continue()
END
//如果存在召唤者，则拿走召唤者身上留存的召唤媒介物（也可能是没用过的，总之会删一个）
IF
	!GlobalGT("moveitem","LOCALS",0)
	Exists(LastSummonerOf())
	OR(3)
		CheckItemSlot(LastSummonerOf(),"SYMUAV3",SLOT_MISC0)
		CheckItemSlot(LastSummonerOf(),"SYMUAV3",SLOT_MISC1)
		CheckItemSlot(LastSummonerOf(),"SYMUAV3",SLOT_MISC2)
THEN
	RESPONSE #100
		SetGlobal("moveitem","LOCALS",7)
		ClearActions(LastSummonerOf())
		ActionOverride(LastSummonerOf(),GiveItem("SYMUAV3",[CONTROLLED.WEAPON.GOLEM.BEHOLDER.NO_MAGIC.BOTH.NEUTRAL]))
END

//如果不存在召唤者，则按距离顺序遍历队员，拿走身上留存的召唤媒介物（也可能是没用过的，总之会删一个）并设置为召唤者
//最近
IF
	!GlobalGT("moveitem","LOCALS",0)
	!Exists(LastSummonerOf())
	OR(3)
		CheckItemSlot([PC],"SYMUAV3",SLOT_MISC0)
		CheckItemSlot([PC],"SYMUAV3",SLOT_MISC1)
		CheckItemSlot([PC],"SYMUAV3",SLOT_MISC2)
THEN
	RESPONSE #100
		SetGlobal("moveitem","LOCALS",1)
		ClearActions([PC])
		ActionOverride([PC],GiveItem("SYMUAV3",[CONTROLLED.WEAPON.GOLEM.BEHOLDER.NO_MAGIC.BOTH.NEUTRAL]))
END

IF
	Global("moveitem","LOCALS",1)
	Global("mycontroller","LOCALS",0)
	InPartySlot([PC],0)
THEN
	RESPONSE #100
		SetGlobal("mycontroller","LOCALS",1)
		Continue()
END

IF
	Global("moveitem","LOCALS",1)
	Global("mycontroller","LOCALS",0)
	InPartySlot([PC],1)
THEN
	RESPONSE #100
		SetGlobal("mycontroller","LOCALS",2)
		Continue()
END

IF
	Global("moveitem","LOCALS",1)
	Global("mycontroller","LOCALS",0)
	InPartySlot([PC],2)
THEN
	RESPONSE #100
		SetGlobal("mycontroller","LOCALS",3)
		Continue()
END

IF
	Global("moveitem","LOCALS",1)
	Global("mycontroller","LOCALS",0)
	InPartySlot([PC],3)
THEN
	RESPONSE #100
		SetGlobal("mycontroller","LOCALS",4)
		Continue()
END

IF
	Global("moveitem","LOCALS",1)
	Global("mycontroller","LOCALS",0)
	InPartySlot([PC],4)
THEN
	RESPONSE #100
		SetGlobal("mycontroller","LOCALS",5)
		Continue()
END

IF
	Global("moveitem","LOCALS",1)
	Global("mycontroller","LOCALS",0)
	InPartySlot([PC],5)
THEN
	RESPONSE #100
		SetGlobal("mycontroller","LOCALS",6)
		Continue()
END
//第二近
IF
	!GlobalGT("moveitem","LOCALS",0)
	!Exists(LastSummonerOf())
	OR(3)
		CheckItemSlot(SecondNearest([PC]),"SYMUAV3",SLOT_MISC0)
		CheckItemSlot(SecondNearest([PC]),"SYMUAV3",SLOT_MISC1)
		CheckItemSlot(SecondNearest([PC]),"SYMUAV3",SLOT_MISC2)
THEN
	RESPONSE #100
		SetGlobal("moveitem","LOCALS",2)
		ClearActions(SecondNearest([PC]))
		ActionOverride(SecondNearest([PC]),GiveItem("SYMUAV3",[CONTROLLED.WEAPON.GOLEM.BEHOLDER.NO_MAGIC.BOTH.NEUTRAL]))
END

IF
	Global("moveitem","LOCALS",2)
	Global("mycontroller","LOCALS",0)
	InPartySlot(SecondNearest([PC]),0)
THEN
	RESPONSE #100
		SetGlobal("mycontroller","LOCALS",1)
		Continue()
END

IF
	Global("moveitem","LOCALS",2)
	Global("mycontroller","LOCALS",0)
	InPartySlot(SecondNearest([PC]),1)
THEN
	RESPONSE #100
		SetGlobal("mycontroller","LOCALS",2)
		Continue()
END

IF
	Global("moveitem","LOCALS",2)
	Global("mycontroller","LOCALS",0)
	InPartySlot(SecondNearest([PC]),2)
THEN
	RESPONSE #100
		SetGlobal("mycontroller","LOCALS",3)
		Continue()
END

IF
	Global("moveitem","LOCALS",2)
	Global("mycontroller","LOCALS",0)
	InPartySlot(SecondNearest([PC]),3)
THEN
	RESPONSE #100
		SetGlobal("mycontroller","LOCALS",4)
		Continue()
END

IF
	Global("moveitem","LOCALS",2)
	Global("mycontroller","LOCALS",0)
	InPartySlot(SecondNearest([PC]),4)
THEN
	RESPONSE #100
		SetGlobal("mycontroller","LOCALS",5)
		Continue()
END

IF
	Global("moveitem","LOCALS",2)
	Global("mycontroller","LOCALS",0)
	InPartySlot(SecondNearest([PC]),5)
THEN
	RESPONSE #100
		SetGlobal("mycontroller","LOCALS",6)
		Continue()
END
//第三近
IF
	!GlobalGT("moveitem","LOCALS",0)
	!Exists(LastSummonerOf())
	OR(3)
		CheckItemSlot(ThirdNearest([PC]),"SYMUAV3",SLOT_MISC0)
		CheckItemSlot(ThirdNearest([PC]),"SYMUAV3",SLOT_MISC1)
		CheckItemSlot(ThirdNearest([PC]),"SYMUAV3",SLOT_MISC2)
THEN
	RESPONSE #100
		SetGlobal("moveitem","LOCALS",3)
		ClearActions(ThirdNearest([PC]))
		ActionOverride(ThirdNearest([PC]),GiveItem("SYMUAV3",[CONTROLLED.WEAPON.GOLEM.BEHOLDER.NO_MAGIC.BOTH.NEUTRAL]))
END

IF
	Global("moveitem","LOCALS",3)
	Global("mycontroller","LOCALS",0)
	InPartySlot(ThirdNearest([PC]),0)
THEN
	RESPONSE #100
		SetGlobal("mycontroller","LOCALS",1)
		Continue()
END

IF
	Global("moveitem","LOCALS",3)
	Global("mycontroller","LOCALS",0)
	InPartySlot(ThirdNearest([PC]),1)
THEN
	RESPONSE #100
		SetGlobal("mycontroller","LOCALS",2)
		Continue()
END

IF
	Global("moveitem","LOCALS",3)
	Global("mycontroller","LOCALS",0)
	InPartySlot(ThirdNearest([PC]),2)
THEN
	RESPONSE #100
		SetGlobal("mycontroller","LOCALS",3)
		Continue()
END

IF
	Global("moveitem","LOCALS",3)
	Global("mycontroller","LOCALS",0)
	InPartySlot(ThirdNearest([PC]),3)
THEN
	RESPONSE #100
		SetGlobal("mycontroller","LOCALS",4)
		Continue()
END

IF
	Global("moveitem","LOCALS",3)
	Global("mycontroller","LOCALS",0)
	InPartySlot(ThirdNearest([PC]),4)
THEN
	RESPONSE #100
		SetGlobal("mycontroller","LOCALS",5)
		Continue()
END

IF
	Global("moveitem","LOCALS",3)
	Global("mycontroller","LOCALS",0)
	InPartySlot(ThirdNearest([PC]),5)
THEN
	RESPONSE #100
		SetGlobal("mycontroller","LOCALS",6)
		Continue()
END
//第四近
IF
	!GlobalGT("moveitem","LOCALS",0)
	!Exists(LastSummonerOf())
	OR(3)
		CheckItemSlot(FourthNearest([PC]),"SYMUAV3",SLOT_MISC0)
		CheckItemSlot(FourthNearest([PC]),"SYMUAV3",SLOT_MISC1)
		CheckItemSlot(FourthNearest([PC]),"SYMUAV3",SLOT_MISC2)
THEN
	RESPONSE #100
		SetGlobal("moveitem","LOCALS",4)
		ClearActions(FourthNearest([PC]))
		ActionOverride(FourthNearest([PC]),GiveItem("SYMUAV3",[CONTROLLED.WEAPON.GOLEM.BEHOLDER.NO_MAGIC.BOTH.NEUTRAL]))
END

IF
	Global("moveitem","LOCALS",4)
	Global("mycontroller","LOCALS",0)
	InPartySlot(FourthNearest([PC]),0)
THEN
	RESPONSE #100
		SetGlobal("mycontroller","LOCALS",1)
		Continue()
END

IF
	Global("moveitem","LOCALS",4)
	Global("mycontroller","LOCALS",0)
	InPartySlot(FourthNearest([PC]),1)
THEN
	RESPONSE #100
		SetGlobal("mycontroller","LOCALS",2)
		Continue()
END

IF
	Global("moveitem","LOCALS",4)
	Global("mycontroller","LOCALS",0)
	InPartySlot(FourthNearest([PC]),2)
THEN
	RESPONSE #100
		SetGlobal("mycontroller","LOCALS",3)
		Continue()
END

IF
	Global("moveitem","LOCALS",4)
	Global("mycontroller","LOCALS",0)
	InPartySlot(FourthNearest([PC]),3)
THEN
	RESPONSE #100
		SetGlobal("mycontroller","LOCALS",4)
		Continue()
END

IF
	Global("moveitem","LOCALS",4)
	Global("mycontroller","LOCALS",0)
	InPartySlot(FourthNearest([PC]),4)
THEN
	RESPONSE #100
		SetGlobal("mycontroller","LOCALS",5)
		Continue()
END

IF
	Global("moveitem","LOCALS",4)
	Global("mycontroller","LOCALS",0)
	InPartySlot(FourthNearest([PC]),5)
THEN
	RESPONSE #100
		SetGlobal("mycontroller","LOCALS",6)
		Continue()
END
//第五近
IF
	!GlobalGT("moveitem","LOCALS",0)
	!Exists(LastSummonerOf())
	OR(3)
		CheckItemSlot(FifthNearest([PC]),"SYMUAV3",SLOT_MISC0)
		CheckItemSlot(FifthNearest([PC]),"SYMUAV3",SLOT_MISC1)
		CheckItemSlot(FifthNearest([PC]),"SYMUAV3",SLOT_MISC2)
THEN
	RESPONSE #100
		SetGlobal("moveitem","LOCALS",5)
		ClearActions(FifthNearest([PC]))
		ActionOverride(FifthNearest([PC]),GiveItem("SYMUAV3",[CONTROLLED.WEAPON.GOLEM.BEHOLDER.NO_MAGIC.BOTH.NEUTRAL]))
END

IF
	Global("moveitem","LOCALS",5)
	Global("mycontroller","LOCALS",0)
	InPartySlot(FifthNearest([PC]),0)
THEN
	RESPONSE #100
		SetGlobal("mycontroller","LOCALS",1)
		Continue()
END

IF
	Global("moveitem","LOCALS",5)
	Global("mycontroller","LOCALS",0)
	InPartySlot(FifthNearest([PC]),1)
THEN
	RESPONSE #100
		SetGlobal("mycontroller","LOCALS",2)
		Continue()
END

IF
	Global("moveitem","LOCALS",5)
	Global("mycontroller","LOCALS",0)
	InPartySlot(FifthNearest([PC]),2)
THEN
	RESPONSE #100
		SetGlobal("mycontroller","LOCALS",3)
		Continue()
END

IF
	Global("moveitem","LOCALS",5)
	Global("mycontroller","LOCALS",0)
	InPartySlot(FifthNearest([PC]),3)
THEN
	RESPONSE #100
		SetGlobal("mycontroller","LOCALS",4)
		Continue()
END

IF
	Global("moveitem","LOCALS",5)
	Global("mycontroller","LOCALS",0)
	InPartySlot(FifthNearest([PC]),4)
THEN
	RESPONSE #100
		SetGlobal("mycontroller","LOCALS",5)
		Continue()
END

IF
	Global("moveitem","LOCALS",5)
	Global("mycontroller","LOCALS",0)
	InPartySlot(FifthNearest([PC]),5)
THEN
	RESPONSE #100
		SetGlobal("mycontroller","LOCALS",6)
		Continue()
END
//第六近
IF
	!GlobalGT("moveitem","LOCALS",0)
	!Exists(LastSummonerOf())
	OR(3)
		CheckItemSlot(SixthNearest([PC]),"SYMUAV3",SLOT_MISC0)
		CheckItemSlot(SixthNearest([PC]),"SYMUAV3",SLOT_MISC1)
		CheckItemSlot(SixthNearest([PC]),"SYMUAV3",SLOT_MISC2)
THEN
	RESPONSE #100
		SetGlobal("moveitem","LOCALS",6)
		ClearActions(SixthNearest([PC]))
		ActionOverride(SixthNearest([PC]),GiveItem("SYMUAV3",[CONTROLLED.WEAPON.GOLEM.BEHOLDER.NO_MAGIC.BOTH.NEUTRAL]))
END

IF
	Global("moveitem","LOCALS",6)
	Global("mycontroller","LOCALS",0)
	InPartySlot(SixthNearest([PC]),0)
THEN
	RESPONSE #100
		SetGlobal("mycontroller","LOCALS",1)
		Continue()
END

IF
	Global("moveitem","LOCALS",6)
	Global("mycontroller","LOCALS",0)
	InPartySlot(SixthNearest([PC]),1)
THEN
	RESPONSE #100
		SetGlobal("mycontroller","LOCALS",2)
		Continue()
END

IF
	Global("moveitem","LOCALS",6)
	Global("mycontroller","LOCALS",0)
	InPartySlot(SixthNearest([PC]),2)
THEN
	RESPONSE #100
		SetGlobal("mycontroller","LOCALS",3)
		Continue()
END

IF
	Global("moveitem","LOCALS",6)
	Global("mycontroller","LOCALS",0)
	InPartySlot(SixthNearest([PC]),3)
THEN
	RESPONSE #100
		SetGlobal("mycontroller","LOCALS",4)
		Continue()
END

IF
	Global("moveitem","LOCALS",6)
	Global("mycontroller","LOCALS",0)
	InPartySlot(SixthNearest([PC]),4)
THEN
	RESPONSE #100
		SetGlobal("mycontroller","LOCALS",5)
		Continue()
END

IF
	Global("moveitem","LOCALS",6)
	Global("mycontroller","LOCALS",0)
	InPartySlot(SixthNearest([PC]),5)
THEN
	RESPONSE #100
		SetGlobal("mycontroller","LOCALS",6)
		Continue()
END

//拿走后摧毁，保证只剩一个
IF
	HasItem("SYMUAV3",Myself)
THEN
	RESPONSE #100
		DestroyItem("SYMUAV3")
		Continue()
END
//拿走后产生一个坏的用来丢地上
IF
	GlobalGT("moveitem","LOCALS",0)
	GlobalLT("moveitem","LOCALS",8)
THEN
	RESPONSE #100
		CreateItem("SYMUAV3A",0,0,0)
		SetGlobal("moveitem","LOCALS",8)
		Continue()
END

//关机
IF
	GlobalLT("mycontroller","LOCALS",2)
	OR(2)
		GlobalTimerExpired("Existime","LOCALS")
		Global("SHUTDOWN","LOCALS",1)
	Range(Player1,4)
THEN
	RESPONSE #100
		GiveItemCreate("SYMUAV3",Player1,0,0,0)
		DestroySelf()
END

IF
	GlobalLT("mycontroller","LOCALS",2)
	OR(2)
		GlobalTimerExpired("Existime","LOCALS")
		Global("SHUTDOWN","LOCALS",1)
	!Range(Player1,4)
THEN
	RESPONSE #100
		DisplayStringHead(Myself,@141)	//返回中……
		MoveToObjectNoInterrupt(Player1)
END

IF
	Global("mycontroller","LOCALS",2)
	OR(2)
		GlobalTimerExpired("Existime","LOCALS")
		Global("SHUTDOWN","LOCALS",1)
	Range(Player2,4)
THEN
	RESPONSE #100
		GiveItemCreate("SYMUAV3",Player2,0,0,0)
		DestroySelf()
END

IF
	Global("mycontroller","LOCALS",2)
	OR(2)
		GlobalTimerExpired("Existime","LOCALS")
		Global("SHUTDOWN","LOCALS",1)
	!Range(Player2,4)
THEN
	RESPONSE #100
		DisplayStringHead(Myself,@141)	//返回中……
		MoveToObjectNoInterrupt(Player2)
END

IF
	Global("mycontroller","LOCALS",3)
	OR(2)
		GlobalTimerExpired("Existime","LOCALS")
		Global("SHUTDOWN","LOCALS",1)
	Range(Player3,4)
THEN
	RESPONSE #100
		GiveItemCreate("SYMUAV3",Player3,0,0,0)
		DestroySelf()
END

IF
	Global("mycontroller","LOCALS",3)
	OR(2)
		GlobalTimerExpired("Existime","LOCALS")
		Global("SHUTDOWN","LOCALS",1)
	!Range(Player3,4)
THEN
	RESPONSE #100
		DisplayStringHead(Myself,@141)	//返回中……
		MoveToObjectNoInterrupt(Player3)
END

IF
	Global("mycontroller","LOCALS",4)
	OR(2)
		GlobalTimerExpired("Existime","LOCALS")
		Global("SHUTDOWN","LOCALS",1)
	Range(Player4,4)
THEN
	RESPONSE #100
		GiveItemCreate("SYMUAV3",Player4,0,0,0)
		DestroySelf()
END

IF
	Global("mycontroller","LOCALS",4)
	OR(2)
		GlobalTimerExpired("Existime","LOCALS")
		Global("SHUTDOWN","LOCALS",1)
	!Range(Player4,4)
THEN
	RESPONSE #100
		DisplayStringHead(Myself,@141)	//返回中……
		MoveToObjectNoInterrupt(Player4)
END

IF
	Global("mycontroller","LOCALS",5)
	OR(2)
		GlobalTimerExpired("Existime","LOCALS")
		Global("SHUTDOWN","LOCALS",1)
	Range(Player5,4)
THEN
	RESPONSE #100
		GiveItemCreate("SYMUAV3",Player5,0,0,0)
		DestroySelf()
END

IF
	Global("mycontroller","LOCALS",5)
	OR(2)
		GlobalTimerExpired("Existime","LOCALS")
		Global("SHUTDOWN","LOCALS",1)
	!Range(Player5,4)
THEN
	RESPONSE #100
		DisplayStringHead(Myself,@141)	//返回中……
		MoveToObjectNoInterrupt(Player5)
END

IF
	Global("mycontroller","LOCALS",6)
	OR(2)
		GlobalTimerExpired("Existime","LOCALS")
		Global("SHUTDOWN","LOCALS",1)
	Range(Player6,4)
THEN
	RESPONSE #100
		GiveItemCreate("SYMUAV3",Player6,0,0,0)
		DestroySelf()
END

IF
	Global("mycontroller","LOCALS",6)
	OR(2)
		GlobalTimerExpired("Existime","LOCALS")
		Global("SHUTDOWN","LOCALS",1)
	!Range(Player6,4)
THEN
	RESPONSE #100
		DisplayStringHead(Myself,@141)	//返回中……
		MoveToObjectNoInterrupt(Player6)
END

//如果中途出问题
IF
	!Allegiance(Myself,CONTROLLED)
THEN
	RESPONSE #100
		ChangeEnemyAlly(Myself,CONTROLLED)
		Continue()
END

//被动模式
IF
	HotKey(D)
THEN
	RESPONSE #100
		ReallyForceSpellRES("SYMUAV1U",Myself)
END
//主动模式
IF
	HotKey(F)
THEN
	RESPONSE #100
		ReallyForceSpellRES("SYMUAV1V",Myself)
END

//和队友太近的话
IF
	OR(3)
		Range([PC],1)
		Range([GOODCUTOFF.0.0.0.0.SUMMONED],1)
		Range([GOODCUTOFF.0.0.0.0.BOTH],1)
THEN
	RESPONSE #100
		JumpToObject(Nearest())
		Continue()
END

//太远的话
IF
	Global("mycontroller","LOCALS",1)
	!Range(Player1,10)
THEN
	RESPONSE #100
		MoveToObject(Player1)
END

IF
	Global("mycontroller","LOCALS",2)
	!Range(Player2,10)
THEN
	RESPONSE #100
		MoveToObject(Player2)
END

IF
	Global("mycontroller","LOCALS",3)
	!Range(Player3,10)
THEN
	RESPONSE #100
		MoveToObject(Player3)
END

IF
	Global("mycontroller","LOCALS",4)
	!Range(Player4,10)
THEN
	RESPONSE #100
		MoveToObject(Player4)
END

IF
	Global("mycontroller","LOCALS",5)
	!Range(Player5,10)
THEN
	RESPONSE #100
		MoveToObject(Player5)
END

IF
	Global("mycontroller","LOCALS",6)
	!Range(Player6,10)
THEN
	RESPONSE #100
		MoveToObject(Player6)
END


//优先攻击伤害操纵者的敌人
IF
	Global("ACTVMODE","LOCALS",1)
	Global("mycontroller","LOCALS",1)
	Global("attackdone","LOCALS",0)
	LOS(LastAttackerOf(Player1),30)
	WeaponEffectiveVs(LastAttackerOf(Player1),MAINHAND)
THEN
	RESPONSE #100
		SetGlobal("attackdone","LOCALS",1)
		AttackReevaluate(LastAttackerOf(Player1),5)
END

IF
	Global("ACTVMODE","LOCALS",1)
	Global("mycontroller","LOCALS",2)
	Global("attackdone","LOCALS",0)
	LOS(LastAttackerOf(Player2),30)
	WeaponEffectiveVs(LastAttackerOf(Player2),MAINHAND)
THEN
	RESPONSE #100
		SetGlobal("attackdone","LOCALS",1)
		AttackReevaluate(LastAttackerOf(Player2),5)
END

IF
	Global("ACTVMODE","LOCALS",1)
	Global("mycontroller","LOCALS",3)
	Global("attackdone","LOCALS",0)
	LOS(LastAttackerOf(Player3),30)
	WeaponEffectiveVs(LastAttackerOf(Player3),MAINHAND)
THEN
	RESPONSE #100
		SetGlobal("attackdone","LOCALS",1)
		AttackReevaluate(LastAttackerOf(Player3),5)
END

IF
	Global("ACTVMODE","LOCALS",1)
	Global("mycontroller","LOCALS",4)
	Global("attackdone","LOCALS",0)
	LOS(LastAttackerOf(Player4),30)
	WeaponEffectiveVs(LastAttackerOf(Player4),MAINHAND)
THEN
	RESPONSE #100
		SetGlobal("attackdone","LOCALS",1)
		AttackReevaluate(LastAttackerOf(Player4),5)
END

IF
	Global("ACTVMODE","LOCALS",1)
	Global("mycontroller","LOCALS",5)
	Global("attackdone","LOCALS",0)
	LOS(LastAttackerOf(Player5),30)
	WeaponEffectiveVs(LastAttackerOf(Player5),MAINHAND)
THEN
	RESPONSE #100
		SetGlobal("attackdone","LOCALS",1)
		AttackReevaluate(LastAttackerOf(Player5),5)
END

IF
	Global("ACTVMODE","LOCALS",1)
	Global("mycontroller","LOCALS",6)
	Global("attackdone","LOCALS",0)
	LOS(LastAttackerOf(Player6),30)
	WeaponEffectiveVs(LastAttackerOf(Player6),MAINHAND)
THEN
	RESPONSE #100
		SetGlobal("attackdone","LOCALS",1)
		AttackReevaluate(LastAttackerOf(Player6),5)
END

//其次在最近七个敌人中找不免疫主手武器的打
IF
	Global("ACTVMODE","LOCALS",1)
	Global("attackdone","LOCALS",0)
	See(NearestEnemyOf())
	WeaponEffectiveVs(NearestEnemyOf(),MAINHAND)
THEN
	RESPONSE #100
		SetGlobal("attackdone","LOCALS",1)
		AttackReevaluate(NearestEnemyOf(),5)
END

IF
	Global("ACTVMODE","LOCALS",1)
	Global("attackdone","LOCALS",0)
	See(SecondNearestEnemyOf())
	WeaponEffectiveVs(SecondNearestEnemyOf(),MAINHAND)
THEN
  RESPONSE #100
		SetGlobal("attackdone","LOCALS",1)
		AttackReevaluate(SecondNearestEnemyOf(),5)
END

IF
	Global("ACTVMODE","LOCALS",1)
	Global("attackdone","LOCALS",0)
	See(ThirdNearestEnemyOf())
	WeaponEffectiveVs(ThirdNearestEnemyOf(),MAINHAND)
THEN
  RESPONSE #100
		SetGlobal("attackdone","LOCALS",1)
		AttackReevaluate(ThirdNearestEnemyOf(),5)
END

IF
	Global("ACTVMODE","LOCALS",1)
	Global("attackdone","LOCALS",0)
	See(FourthNearestEnemyOf())
	WeaponEffectiveVs(FourthNearestEnemyOf(),MAINHAND)
THEN
  RESPONSE #100
		SetGlobal("attackdone","LOCALS",1)
		AttackReevaluate(FourthNearestEnemyOf(),5)
END

IF
	Global("ACTVMODE","LOCALS",1)
	Global("attackdone","LOCALS",0)
	See(FifthNearestEnemyOf())
	WeaponEffectiveVs(FifthNearestEnemyOf(),MAINHAND)
THEN
  RESPONSE #100
		SetGlobal("attackdone","LOCALS",1)
		AttackReevaluate(FifthNearestEnemyOf(),5)
END

IF
	Global("ACTVMODE","LOCALS",1)
	Global("attackdone","LOCALS",0)
	See(SixthNearestEnemyOf())
	WeaponEffectiveVs(SixthNearestEnemyOf(),MAINHAND)
THEN
  RESPONSE #100
		SetGlobal("attackdone","LOCALS",1)
		AttackReevaluate(SixthNearestEnemyOf(),5)
END

IF
	Global("ACTVMODE","LOCALS",1)
	Global("attackdone","LOCALS",0)
	See(SeventhNearestEnemyOf())
	WeaponEffectiveVs(SeventhNearestEnemyOf(),MAINHAND)
THEN
  RESPONSE #100
		SetGlobal("attackdone","LOCALS",1)
		AttackReevaluate(SeventhNearestEnemyOf(),5)
END

//计时
IF
	Global("attackdone","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobalTimer("attackonce","LOCALS",2)
		SetGlobal("attackdone","LOCALS",2)
	RESPONSE #100
		SetGlobalTimer("attackonce","LOCALS",1)
		SetGlobal("attackdone","LOCALS",2)
END

IF
	GlobalTimerExpired("attackonce","LOCALS")
THEN
	RESPONSE #100
		SetGlobal("attackdone","LOCALS",0)
END

//跟随
IF
	Global("mycontroller","LOCALS",1)
	OR(2)
		!See(NearestEnemyOf())
		Global("attackdone","LOCALS",2)
THEN
	RESPONSE #100
		FollowObjectFormation(Player1,2,2)
	RESPONSE #100
		FollowObjectFormation(Player1,-2,2)
	RESPONSE #100
		FollowObjectFormation(Player1,2,-2)
	RESPONSE #100
		FollowObjectFormation(Player1,-2,-2)
END

IF
	Global("mycontroller","LOCALS",2)
	OR(2)
		!See(NearestEnemyOf())
		Global("attackdone","LOCALS",2)
THEN
	RESPONSE #100
		FollowObjectFormation(Player2,2,2)
	RESPONSE #100
		FollowObjectFormation(Player2,-2,2)
	RESPONSE #100
		FollowObjectFormation(Player2,2,-2)
	RESPONSE #100
		FollowObjectFormation(Player2,-2,-2)
END

IF
	Global("mycontroller","LOCALS",3)
	OR(2)
		!See(NearestEnemyOf())
		Global("attackdone","LOCALS",2)
THEN
	RESPONSE #100
		FollowObjectFormation(Player3,2,2)
	RESPONSE #100
		FollowObjectFormation(Player3,-2,2)
	RESPONSE #100
		FollowObjectFormation(Player3,2,-2)
	RESPONSE #100
		FollowObjectFormation(Player3,-2,-2)
END

IF
	Global("mycontroller","LOCALS",4)
	OR(2)
		!See(NearestEnemyOf())
		Global("attackdone","LOCALS",2)
THEN
	RESPONSE #100
		FollowObjectFormation(Player4,2,2)
	RESPONSE #100
		FollowObjectFormation(Player4,-2,2)
	RESPONSE #100
		FollowObjectFormation(Player4,2,-2)
	RESPONSE #100
		FollowObjectFormation(Player4,-2,-2)
END

IF
	Global("mycontroller","LOCALS",5)
	OR(2)
		!See(NearestEnemyOf())
		Global("attackdone","LOCALS",2)
THEN
	RESPONSE #100
		FollowObjectFormation(Player5,2,2)
	RESPONSE #100
		FollowObjectFormation(Player5,-2,2)
	RESPONSE #100
		FollowObjectFormation(Player5,2,-2)
	RESPONSE #100
		FollowObjectFormation(Player5,-2,-2)
END

IF
	Global("mycontroller","LOCALS",6)
	OR(2)
		!See(NearestEnemyOf())
		Global("attackdone","LOCALS",2)
THEN
	RESPONSE #100
		FollowObjectFormation(Player6,2,2)
	RESPONSE #100
		FollowObjectFormation(Player6,-2,2)
	RESPONSE #100
		FollowObjectFormation(Player6,2,-2)
	RESPONSE #100
		FollowObjectFormation(Player6,-2,-2)
END

